language: elixir
notifications:
  recipients:
    - eduardo@gurgel.me
elixir:
  - 0.14.1
  - 0.14.2
  - 0.14.3
  - 0.15.0
  - 0.15.1
  - 1.0.0
otp_release:
  - 17.0
  - 17.1
script: mix test --no-start
env: MIX_ENV=test
